Script started on Fri Mar 15 20:17:29 2024
[1m[7m%[27m[1m[0m                                                                                ]7;file://Ethans-MacBook-Air-8.local/Users/ethanchapman[0m[27m[24m[Jethanchapman@Ethans-MacBook-Air-8 ~ % [K[?2004h../Ethan_Chapman_3[?2004l
zsh: no such file or directory: ./Ethan_Chapman_3
[1m[7m%[27m[1m[0m                                                                                ]7;file://Ethans-MacBook-Air-8.local/Users/ethanchapman[0m[27m[24m[Jethanchapman@Ethans-MacBook-Air-8 ~ % [K[?2004h../Ethan_Chapman_3.cpp[?2004l
zsh: permission denied: ./Ethan_Chapman_3.cpp
[1m[7m%[27m[1m[0m                                                                                ]7;file://Ethans-MacBook-Air-8.local/Users/ethanchapman[0m[27m[24m[Jethanchapman@Ethans-MacBook-Air-8 ~ % [K[?2004heexit[?2004l

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       9 completed.

Script done on Fri Mar 15 20:18:09 2024
